-- Seed Data: Belgium Job Contract Types
-- To be run after 20251105213527_catalog_dictionaries.sql migration

INSERT INTO public.job_contract_types (slug, name_nl, name_fr, name_en, description_nl, description_fr, description_en, sort_order) VALUES
  ('cdi', 
   'Contract van onbepaalde duur', 
   'Contrat à durée indéterminée', 
   'Permanent Contract',
   'Vast contract zonder einddatum',
   'Contrat permanent sans date de fin',
   'Permanent contract without end date',
   1),
  
  ('cdd', 
   'Contract van bepaalde duur', 
   'Contrat à durée déterminée', 
   'Fixed-Term Contract',
   'Tijdelijk contract met vaste einddatum',
   'Contrat temporaire avec date de fin fixe',
   'Temporary contract with fixed end date',
   2),
  
  ('interim', 
   'Uitzendwerk', 
   'Intérim', 
   'Temporary Agency Work',
   'Tijdelijk werk via uitzendbureau',
   'Travail temporaire via agence',
   'Temporary work via agency',
   3),
  
  ('flexi', 
   'Flexijob', 
   'Flexijob', 
   'Flexi-Job',
   'Flexibel bijverdienste contract (max 500u/jaar)',
   'Contrat flexible complémentaire (max 500h/an)',
   'Flexible supplementary contract (max 500h/year)',
   4),
  
  ('student', 
   'Studentenjob', 
   'Job étudiant', 
   'Student Job',
   'Contract voor studenten (max 600u/jaar)',
   'Contrat pour étudiants (max 600h/an)',
   'Contract for students (max 600h/year)',
   5),
  
  ('freelance', 
   'Zelfstandige', 
   'Indépendant', 
   'Freelance/Self-Employed',
   'Werk als zelfstandige ondernemer',
   'Travail en tant qu''indépendant',
   'Work as self-employed',
   6),
  
  ('internship', 
   'Stage', 
   'Stage', 
   'Internship',
   'Stage als deel van opleiding',
   'Stage dans le cadre d''une formation',
   'Internship as part of education',
   7),
  
  ('replacement', 
   'Vervanging', 
   'Remplacement', 
   'Replacement Contract',
   'Tijdelijke vervanging van werknemer',
   'Remplacement temporaire d''un employé',
   'Temporary replacement of employee',
   8),
  
  ('seasonal', 
   'Seizoensarbeid', 
   'Travail saisonnier', 
   'Seasonal Work',
   'Werk gebonden aan bepaald seizoen',
   'Travail lié à une saison spécifique',
   'Work tied to specific season',
   9),
  
  ('part_time', 
   'Deeltijds', 
   'Temps partiel', 
   'Part-Time',
   'Werk minder dan voltijds',
   'Travail à temps partiel',
   'Work less than full-time',
   10),
  
  ('apprenticeship', 
   'Leercontract', 
   'Contrat d''apprentissage', 
   'Apprenticeship',
   'Leren en werken tegelijk',
   'Apprendre et travailler simultanément',
   'Learn and work simultaneously',
   11)
ON CONFLICT (slug) DO NOTHING;

