-- CHAT-001: Chat tables migration
-- Creates conversations, conversation_participants, and messages tables
-- Includes indexes, triggers, and foreign key constraints

-- 1. Conversations table
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  advert_id uuid references public.adverts(id) on delete set null,
  last_message_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. Conversation participants table
create table if not exists public.conversation_participants (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'peer')),
  muted boolean default false,
  last_read_at timestamptz,
  created_at timestamptz default now(),
  primary key (conversation_id, user_id)
);

-- 3. Messages table
create table if not exists public.messages (
  id bigint primary key generated by default as identity,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. Indexes for performance
create index if not exists idx_conversations_created_by on public.conversations(created_by);
create index if not exists idx_conversations_advert_id on public.conversations(advert_id);
create index if not exists idx_conversations_last_message_at on public.conversations(last_message_at desc nulls last);

create index if not exists idx_conversation_participants_user_id on public.conversation_participants(user_id);
create index if not exists idx_conversation_participants_conversation_id on public.conversation_participants(conversation_id);

create index if not exists idx_messages_conversation_created on public.messages(conversation_id, created_at desc);
create index if not exists idx_messages_author on public.messages(author_id, created_at desc);

-- 5. Triggers for updated_at
create trigger set_updated_at_conversations
  before update on public.conversations
  for each row
  execute function public.set_updated_at();

create trigger set_updated_at_messages
  before update on public.messages
  for each row
  execute function public.set_updated_at();

-- 6. Trigger to update last_message_at in conversations when a new message is inserted
create or replace function public.update_conversation_last_message_at()
returns trigger
language plpgsql
security definer
as $$
begin
  update public.conversations
  set last_message_at = new.created_at
  where id = new.conversation_id;
  return new;
end;
$$;

create trigger update_conversation_last_message_trigger
  after insert on public.messages
  for each row
  execute function public.update_conversation_last_message_at();

